# This is a basic workflow to help you get started with Actions

name: CI

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          TAG=${GITHUB_REF/refs\/tags\//}
          VERSION=''
          PREFIX=${TAG_VERSION:0:1}
          if [ "${PREFIX,,}" == "v" ]; then VERSION="${TAG:1}"; else VERSION="${TAG:0}"; fi
          echo $VERSION
