# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: # This configuration does not affect the page_build event above
      - main
      

jobs:
  build:
    runs-on: ubuntu-latest
    steps:



      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/marloncoti/my-foo-python-package/releases/latest
          owner: octokit
          repo: request-action
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      - run: "echo latest release: ${{ steps.get_latest_release.outputs.data }}"